### ISSUE TITLE
Feature Request/Proposal - configure bean initialization strategy

### ISSUE THREAD

**Issue by jkatnik** [ocadotechnology/test-arranger#46]
Hello,

currently in TestArranger doesn't assign random values if the Kotlin constructor has default values.
I was explained that this is a design choice within the Ocado organization.

As an external user, I'd like to be able to change that behavior via the properties file so that Test Arranger would fit my project needs.

```
data class Foo(
  val foo: String = "",
)

@Test
fun testSomeMethod() {
  val random = some<Foo>()
  assertThat(random.foo).isNotEmpty
}
```

**Comment by mjureczko** [comment]
Related issue: https://github.com/jkatnik/test-arranger/commit/469789ca192675e1f0b7c0b5ccfa164c6f3affd3

**Comment by jkatnik** [comment]
Hi @mjureczko 

thank you for introducing that change so quickly.

Unfortunately, it doesn't;t work with Spring 2.7 because it is using Kotlin 1.6. by default.

using: testImplementation 'com.ocadotechnology.gembus:test-arranger:1.4.6
![image](https://user-images.githubusercontent.com/7869474/212840032-8f598675-fd1e-4469-9a78-6cec2d39f252.png)

I haven't reported it earlier because I was hoping that I could convince my stakeholders to upgrade to spring boot 3.

**Comment by mjureczko** [comment]
Let me know if you can instantiate Foo using the arranger's java method, i.e.: `Arranger.some(Foo::class.java)`.

Anyway, test-arranger does not depend on new Kotlin features, so I can change the Kotlin dependency to a lesser version on the 1.4 line.

**Comment by jkatnik** [comment]
@mjureczko regarding downgrading the Kotlin version in 1.4.x - it is a good idea, please release in your spare time, no hurry :)

**Comment by mjureczko** [comment]
@jkatnik version 1.4.6.1, with downgraded kotlin dependency, has been released

**Comment by jkatnik** [comment]
@mjureczko thanks!
